imports:
    - { resource: config.yml }

framework:
    session:
      handler_id: session.handler.memcached

doctrine:
    orm:
        metadata_cache_driver:
            type: memcached
            host: localhost
            port: 11211
            instance_class: Memcached
        #query_cache_driver:
        #    type: memcached
        #    host: localhost
        #    port: 11211
        #    instance_class: Memcached
#        result_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warning
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

services:
    session.memcached:
        class: Memcached
        arguments:
            persistent_id: "units"
        calls:
            - [ addServer, [ "localhost", 11211 ]]

    session.handler.memcached:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: [@session.memcached, { prefix: "units_sessions_", expiretime: 3600 }]
