MyCLabs\UnitBundle\Entity\PhysicalQuantity\PhysicalQuantity:
  type: entity

  gedmo:
    translation:
      locale: translatableLocale

  id:
    id:
      type: string

  fields:
    label:
      type: string
      nullable: true
      gedmo:
        - translatable
    symbol:
      type: string
      nullable : true
    isBase:
      type: boolean

  manyToOne:
    referenceUnit:
      targetEntity: MyCLabs\UnitBundle\Entity\Unit\StandardUnit
      joinColumn:
        nullable: true

  oneToMany:
    physicalQuantityComponents:
      targetEntity: Component
      mappedBy: derivedPhysicalQuantity
