MyCLabs\UnitBundle\Entity\PhysicalQuantity\PhysicalQuantity:
  type: entity

  inheritanceType: JOINED
  discriminatorColumn:
    name: quantity_type
    type: string
  discriminatorMap:
    standard: BasePhysicalQuantity
    discrete: DerivedPhysicalQuantity

  gedmo:
    translation:
      locale: translatableLocale

  id:
    id:
      type: string

  fields:
    label:
      type: string
      nullable: true
      gedmo:
        - translatable
    symbol:
      type: string
      nullable : true

  manyToOne:
    unitOfReference:
      targetEntity: MyCLabs\UnitBundle\Entity\Unit\StandardUnit
      joinColumn:
        nullable: true

  oneToMany:
    units:
      targetEntity: MyCLabs\UnitBundle\Entity\Unit\StandardUnit
      mappedBy: physicalQuantity
