MyCLabs\UnitBundle\Entity\PhysicalQuantity\Component:
  type: entity

  id:
    derivedPhysicalQuantity:
      associationKey: true
    basePhysicalQuantity:
      associationKey: true

  fields:
    exponent:
      type: integer

  manyToOne:
    derivedPhysicalQuantity:
      targetEntity: PhysicalQuantity
      inversedBy: physicalQuantityComponents
    basePhysicalQuantity:
      targetEntity: PhysicalQuantity
