MyCLabs\UnitBundle\Entity\PhysicalQuantity\Component:
  type: entity

  id:
    derivedQuantity:
      associationKey: true
    baseQuantity:
      associationKey: true

  fields:
    exponent:
      type: integer

  manyToOne:
    derivedQuantity:
      targetEntity: DerivedPhysicalQuantity
      inversedBy: components
    baseQuantity:
      targetEntity: BasePhysicalQuantity
