MyCLabs\UnitBundle\Entity\PhysicalQuantity\PhysicalQuantity:
  type: entity

  inheritanceType: JOINED
  discriminatorColumn:
    name: quantity_type
    type: string
  discriminatorMap:
    standard: BasePhysicalQuantity
    discrete: DerivedPhysicalQuantity

  id:
    id:
      type: string

  fields:
    symbol:
      type: string
      nullable : true

  embedded:
    label:
      class: MyCLabs\UnitBundle\Entity\TranslatedString

  manyToOne:
    unitOfReference:
      targetEntity: MyCLabs\UnitBundle\Entity\Unit\StandardUnit
      joinColumn:
        nullable: true

  oneToMany:
    units:
      targetEntity: MyCLabs\UnitBundle\Entity\Unit\StandardUnit
      mappedBy: physicalQuantity
