MyCLabs\UnitBundle\Entity\PhysicalQuantity\DerivedPhysicalQuantity:
  type: entity

  oneToMany:
    components:
      targetEntity: Component
      mappedBy: derivedQuantity
      cascade: [ all ]
      orphanRemoval: true
