MyCLabs\UnitBundle\Entity\Unit\Unit:
  type: entity
  repositoryClass: MyCLabs\UnitBundle\Repository\DoctrineUnitRepository

  inheritanceType: JOINED
  discriminatorColumn:
    name: unit_type
    type: string
  discriminatorMap:
    standard: StandardUnit
    discrete: DiscreteUnit

  id:
    id:
      type: string

  embedded:
    label:
      class: MyCLabs\UnitBundle\Entity\TranslatedString
    symbol:
      class: MyCLabs\UnitBundle\Entity\TranslatedString
