MyCLabs\UnitBundle\Entity\Unit\Unit:
  type: entity

  inheritanceType: JOINED
  discriminatorColumn:
    name: unit_type
    type: string
  discriminatorMap:
    standard: StandardUnit
    discrete: DiscreteUnit

  gedmo:
    translation:
      locale: translatableLocale

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    label:
      type: string
      nullable: true
      gedmo:
        - translatable
    symbol:
      type: string
      gedmo:
        - translatable
