locale_redirection:
    pattern:  "/"
    defaults: { _controller: MyCLabs\UnitBundle\Controller\DefaultController:localeRedirectionAction }

homepage:
    pattern:  "{_locale}/"
    defaults: { _controller: MyCLabs\UnitBundle\Controller\DefaultController:homeAction }

physical_quantity_list:
    pattern:  "{_locale}/physicalquantity/list"
    defaults: { _controller: MyCLabs\UnitBundle\Controller\PhysicalQuantityController:listAction }
unit_list:
    pattern:  "{_locale}/unit/list"
    defaults: { _controller: MyCLabs\UnitBundle\Controller\UnitController:listAction }
unit_conversion:
    pattern:  "{_locale}/unit/conversion"
    defaults: { _controller: MyCLabs\UnitBundle\Controller\UnitController:conversionAction }

# API

api_unit_system:
    type: rest
    resource: MyCLabs\UnitBundle\Controller\API\UnitSystemController
    prefix: "api/"
api_physical_quantity:
    type: rest
    resource: MyCLabs\UnitBundle\Controller\API\PhysicalQuantityController
    prefix: "api/"
api_unit:
    type: rest
    resource: MyCLabs\UnitBundle\Controller\API\UnitController
    prefix: "api/"
api_operation:
    type: rest
    resource: MyCLabs\UnitBundle\Controller\API\OperationController
    prefix: "api/"
