locale_redirection:
    pattern:  "/"
    defaults: { _controller: UnitBundle:Default:localeRedirection }

homepage:
    pattern:  "{_locale}/"
    defaults: { _controller: UnitBundle:Default:home }

physical_quantity_list:
    pattern:  "{_locale}/physicalquantity/list"
    defaults: { _controller: UnitBundle:PhysicalQuantity:list }
unit_list:
    pattern:  "{_locale}/unit/list"
    defaults: { _controller: UnitBundle:Unit:list }
unit_conversion:
    pattern:  "{_locale}/unit/conversion"
    defaults: { _controller: UnitBundle:Unit:conversion }

# API

api_unit_system:
    type: rest
    resource: MyCLabs\UnitBundle\Controller\API\UnitSystemController
    prefix: api
api_physical_quantity:
    type: rest
    resource: MyCLabs\UnitBundle\Controller\API\PhysicalQuantityController
    prefix: api
api_unit:
    type: rest
    resource: MyCLabs\UnitBundle\Controller\API\UnitController
    prefix: api
api_operation:
    type: rest
    resource: MyCLabs\UnitBundle\Controller\API\OperationController
    prefix: api
