parameters:
#    unit.example.class: MyCLabs\UnitBundle\Example

services:

    unit.repository.unit:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - MyCLabs\UnitBundle\Entity\Unit\Unit

    unit.service.operation:
        class: MyCLabs\UnitBundle\Service\OperationService
        arguments:
            - "@unit.service.parser"

    unit.service.parser:
        class: MyCLabs\UnitBundle\Service\UnitExpressionParser
        arguments:
            - "@unit.service.lexer"
            - "@unit.repository.unit"
    unit.service.lexer:
        class: MyCLabs\UnitBundle\Service\UnitExpressionParser\UnitExpressionLexer

    unit.dtoFactory.unitSystem:
        class: MyCLabs\UnitBundle\Service\DTOFactory\UnitSystemDTOFactory
    unit.dtoFactory.physicalQuantity:
        class: MyCLabs\UnitBundle\Service\DTOFactory\PhysicalQuantityDTOFactory
    unit.dtoFactory.unit:
        class: MyCLabs\UnitBundle\Service\DTOFactory\UnitDTOFactory

    serializer.property_normalizer:
        class: MyCLabs\UnitBundle\Service\Serializer\PropertyNormalizer
        tags:
            - { name: serializer.normalizer }
